fe-lang/sonatina

crates/codegen/src/critical_edge.rs
crates/codegen/src/domtree.rs
crates/codegen/src/lib.rs
crates/codegen/src/loop_analysis.rs
crates/codegen/src/optim/gvn.rs
crates/codegen/src/optim/licm.rs
crates/codegen/src/optim/sccp.rs
crates/codegen/src/post_domtree.rs
crates/filecheck/src/gvn.rs
crates/filecheck/src/licm.rs
crates/filecheck/src/sccp.rs
crates/ir/Cargo.toml
crates/ir/src/cfg.rs
crates/ir/src/dfg.rs
crates/ir/src/function.rs
crates/ir/src/graphviz/block.rs
crates/ir/src/graphviz/function.rs
crates/ir/src/graphviz/mod.rs
crates/ir/src/insn.rs
crates/ir/src/lib.rs
crates/ir/src/module.rs
crates/ir/src/types.rs
crates/ir/src/value.rs

Implement graphviz for sonatina IR with dot2 crate.

Implement graphviz

---

crates/ir/src/insn.rs
crates/parser/src/lexer.rs
crates/parser/src/parser.rs

1. Fix invalid tokenization in `parser`
2. Add missing `args` handling for `gep`
3. Fix the wrong result type calculation

Fix `gep` related calculation

---

crates/ir/src/bigint.rs

Bug fix for casting to sonatina type `I256` for minimum signed type

Cast minimum signed type to I256

---

crates/ir/src/builder/module_builder.rs
crates/ir/src/function.rs
crates/parser/src/parser.rs

This change allows forward function declaration in sonatina file format to test mutually recursive functions.

Allow forward function declaration in sonatina file format

---

crates/ir/src/dfg.rs
crates/ir/src/graphviz/function.rs
crates/ir/src/insn.rs
crates/ir/src/value.rs

- Replace `DisplayArgValues` type with simpler representation as atomic `DisplayArgValue`s.
- Add utility method for displaying list of arguments.

Refactor display type for instruction arguments

---

crates/ir/src/function.rs
crates/ir/src/insn.rs
crates/ir/src/module.rs

Fix lifetime bug introduced in graphviz PR: unjustified assumption about same lifetime on references nested in `DisplaySignature` and `DisplayCalleeFuncRef` type.

Fix lifetime bug

---

Cargo.toml
crates/interpreter/Cargo.toml
crates/interpreter/src/frame.rs
crates/interpreter/src/lib.rs
crates/interpreter/src/pc.rs
crates/interpreter/src/state.rs
crates/interpreter/src/types.rs
crates/interpreter/src/value.rs
crates/ir/src/bigint.rs
crates/ir/src/builder/func_builder.rs
crates/ir/src/builder/module_builder.rs
crates/ir/src/value.rs

Implements interpreter state and instruction execution for sonatina IR
- operates on module-level
- handles constant global values

Implement interpreter

---

crates/interpreter/src/types.rs
crates/ir/src/module.rs

Replaces `Mutex` with `RwLock` for recursive read of ty store and gv store.

Permit recursive read of type store and gv store

---

Cargo.toml

Removes compilation warning about different resolver in crates and workspace.

Specify non-default workspace resolver

---

crates/codegen/src/loop_analysis.rs
crates/codegen/src/optim/simplify_impl.rs
crates/codegen/src/optim/simplify_impl/expr.isle
crates/filecheck/fixtures/gvn/commutativity.sntn
crates/filecheck/fixtures/gvn/llvm_phi-of-ops-move-block.sntn
crates/filecheck/fixtures/gvn/value_phi_loop.sntn
crates/filecheck/fixtures/licm/basic.sntn
crates/filecheck/fixtures/sccp/complex_loop.sntn
crates/filecheck/fixtures/sccp/const_loop.sntn
crates/ir/src/builder/func_builder.rs
crates/ir/src/graphviz/mod.rs
crates/ir/src/insn.rs
crates/ir/src/ir_writer.rs
crates/parser/src/lexer.rs
crates/parser/src/parser.rs

The JumpOp fallthrough/jump distinction doesn't seem useful. Block order may change during optimization; rather than ensuring that optimizations update the JumpOp accordingly, codegen should instead check if the jumped-to block follows the current block to determine whether a jump operation is necessary.

Remove JumpOp from Jump insn; remove "fallthrough" op in text repr

---

crates/codegen/src/optim/gvn.rs
crates/codegen/src/optim/licm.rs
crates/codegen/src/optim/sccp.rs
crates/codegen/src/optim/simplify_impl.rs
crates/filecheck/fixtures/adce/all_dests_remove.sntn
crates/filecheck/fixtures/adce/whole_loop_removed.sntn
crates/filecheck/fixtures/gvn/fold_predicted_value.sntn
crates/filecheck/fixtures/insn_simplify/neg.sntn
crates/interpreter/src/state.rs
crates/ir/src/dfg.rs
crates/ir/src/insn.rs
crates/ir/src/ir_writer.rs
crates/ir/src/types.rs
crates/ir/src/value.rs
crates/parser/Cargo.toml
crates/parser/src/error.rs
crates/parser/src/lib.rs
crates/parser/test_files/errors/type_err.snap
crates/parser/test_files/errors/type_err.sntn
crates/parser/test_files/errors/undefined.snap

The new parser's use of aliases revealed some alias-related bugs in some of the optimizations. The cleanest fix for this is to just remove `ValueData::Alias`, and instead replace the uses of the alias `Value` with the original `Value` (which is easy, because the dfg already tracks which instructions use each `Value`.)
I also changed the parser so that it no longer uses aliases. The prior method of handling values in the parser lead to the wrong type being assigned to some insn result values (in cases where the first argument to some insn was a value whose definition had not yet been seen by the parser). The new method is to first do a pass over all statements in a function to "declare" all values with their proper types (by calling `dfg.make_value` with dummy `ValueData`).

Remove ValueData::Alias

---

crates/ir/src/global_variable.rs

Defines `DisplayGlobalVariable` and `DisplayGlobalVariableData`

Display `GlobalVariable`

---

crates/ir/src/types.rs

Implements `cranelift_entity::ReservedValue` for `Type`, to use as `PackedOption`

Implement `cranelift_entity::ReservedValue` for `Type`

---

crates/ir/src/inst/control_flow.rs
crates/ir/src/inst/evm/mod.rs
crates/ir/src/inst/inst_set.rs
crates/ir/src/inst/mod.rs
crates/ir/src/lib.rs
crates/macros/src/inst.rs
crates/macros/src/inst_set.rs
crates/macros/src/inst_set_base.rs

The new implementation of `BranchInfo` would be a nice example of this change.
```rust
pub trait InstDowncast: Sized {
fn downcast(isb: &dyn InstSetBase, inst: &dyn Inst) -> Option<Self>;
fn map<F, R>(isb: &dyn InstSetBase, inst: &dyn Inst, f: F) -> Option<R>
where
F: Fn(Self) -> R,
{
let data = Self::downcast(isb, inst)?;
Some(f(data))
}
}
#[derive(Clone, Copy)]
pub enum BranchInfo<'i> {
Jump(&'i Jump),
Br(&'i Br),
BrTable(&'i BrTable),
}
impl<'i> InstDowncast for BranchInfo<'i> {
fn downcast(isb: &dyn crate::InstSetBase, inst: &dyn super::Inst) -> Option<Self> {
InstDowncast::map(isb, inst, BranchInfo::Jump)
.or_else(|| InstDowncast::map(isb, inst, BranchInfo::Br))
.or_else(|| InstDowncast::map(isb, inst, BranchInfo::BrTable))
}
}
```
NOTE: `Inst` derive macro automatically implements …

Flexible inst cast

---

crates/verifier/Cargo.toml
crates/verifier/src/error/kind.rs
crates/verifier/src/error/mod.rs
crates/verifier/src/error_stack.rs
crates/verifier/src/lib.rs
crates/verifier/src/pass/mod.rs

- Defines verifier `ErrorStack`.
- Adds mappings from `ErrorKind` to `IrSource` (function, block, instruction, etc.)

Define `sonatina_verifier::ErrorStack`

---

crates/codegen/src/optim/adce.rs
crates/codegen/src/optim/licm.rs
crates/codegen/src/optim/sccp.rs
crates/ir/src/dfg.rs
crates/ir/src/inst/control_flow.rs
crates/ir/src/inst/data.rs
crates/ir/src/inst/evm/mod.rs
crates/ir/src/inst/mod.rs
crates/macros/src/inst.rs

Please start reviewing after #69.
I've added the SideEffect enum. In the current implementation, only `None`, `Read`, `Write` can be specified. `Read` can be analogized to reading from memory. While it does not affect the state, it indicates that it can be influenced by the state. `Write` can be analogized to writing to memory, and it affects the state.
This is a very simple model, but it provides **minimal** necessary information for several optimizations, such as ADCE (Aggressive Dead Code Elimination) and instruction reordering, which I feel can have a relatively significant impact.
In the future, I would like to have a more rigorous model, and I plan to work on that in collaboration with Lane.

Introduce `SideEffect`

---

crates/ir/src/dfg.rs
crates/ir/src/inst/control_flow.rs
crates/ir/src/inst/inst_set.rs
crates/ir/src/inst/mod.rs
crates/ir/src/lib.rs
crates/macros/src/inst.rs
crates/macros/src/inst_set_base.rs
crates/parser/src/inst/arith.rs
crates/parser/src/inst/cast.rs
crates/parser/src/inst/cmp.rs
crates/parser/src/inst/control_flow.rs
crates/parser/src/inst/data.rs
crates/parser/src/inst/evm/mod.rs
crates/parser/src/inst/logic.rs
crates/parser/src/inst/mod.rs

Define `InstExt` that contains a method that can't be included in `Inst` for trait object safety(currently, only the `belongs_to` method is defined. `Inst` macro implements `InstExt` internally.

Define `InstExt`

---

crates/verifier/src/ctx.rs
crates/verifier/src/error_stack.rs
crates/verifier/src/lib.rs
crates/verifier/src/pass.rs

Defines `VerificationPass` and `VerificationCtx`

Verification pass

---

crates/codegen/src/critical_edge.rs
crates/codegen/src/domtree.rs
crates/codegen/src/loop_analysis.rs
crates/codegen/src/post_domtree.rs
crates/filecheck/src/lib.rs
crates/interpreter/src/lib.rs
crates/interpreter/tests/common.rs
crates/ir/src/builder/mod.rs
crates/ir/src/builder/module_builder.rs
crates/ir/src/global_variable.rs
crates/ir/src/graphviz/mod.rs
crates/ir/src/inst/data.rs
crates/ir/src/inst/evm/mod.rs
crates/ir/src/ir_writer.rs
crates/ir/src/module.rs
crates/parser/test_files/syntax/module/func_type.ir.snap
crates/parser/test_files/syntax/module/global_variable.ir.snap
crates/parser/test_files/syntax/module/newlines.ir.snap
crates/parser/test_files/syntax/module/simple.ir.snap
crates/verifier/src/error/mod.rs

@sbillig Sorry, I forgot to include this fix in #85.
* Rename `Module::funcs` -> `Module::func_store`
* Insert newlines properly between declarations
* Fix `InstWrite` impl for `EvmContractSize/GetFunctionPtr`
Regarding to `InstWrite` macro, I'll tweak `impl_inst_write` macro a little bit in another PR.

Add newlines properly in `ModuleWriter`

---

crates/codegen/src/loop_analysis.rs
crates/codegen/src/optim/sccp.rs
crates/ir/src/cfg.rs
crates/ir/src/dfg.rs
crates/ir/src/function.rs
crates/ir/src/global_variable.rs
crates/ir/src/graphviz/block.rs
crates/ir/src/graphviz/function.rs
crates/ir/src/inst/arith.rs
crates/ir/src/inst/cast.rs
crates/ir/src/inst/cmp.rs
crates/ir/src/inst/control_flow.rs
crates/ir/src/inst/data.rs
crates/ir/src/inst/evm/mod.rs
crates/ir/src/inst/logic.rs
crates/ir/src/inst/mod.rs
crates/ir/src/ir_writer.rs
crates/ir/src/layout.rs
crates/ir/src/linkage.rs
crates/ir/src/module.rs
crates/ir/src/types.rs
crates/ir/src/value.rs
crates/macros/src/inst.rs
crates/parser/src/lib.rs
crates/parser/src/syntax.rs
crates/parser/tests/syntax.rs
crates/verifier/src/error/kind.rs
crates/verifier/src/error/mod.rs
crates/verifier/src/error/trace_info.rs

This PR mainly just refactored ir write related thing, and also fixed wrong terminator marker for call inst.

Refactor ir writer

---

crates/filecheck/src/lib.rs
crates/ir/src/builder/mod.rs
crates/ir/src/builder/module_builder.rs
crates/ir/src/global_variable.rs
crates/ir/src/graphviz/block.rs
crates/ir/src/module_linker.rs
crates/ir/src/value.rs
crates/parser/src/error.rs
crates/parser/src/lib.rs
crates/parser/tests/syntax.rs
crates/triple/src/lib.rs

This change modifies `declare_function` as suggested by the maintainers in issue #91.
Note: During integration testing, I discovered a panic in the parser crate when declaring two functions:
```
rust
%foo() -> unit { return; }
%foo(i8) -> i8 { return 0.i8; }
```
The panic occurs at line 160 in `lib.rs` of the parser, caused by an attempt to access arguments of the first function. This issue appears only with constant-return functions and depends on the declaration order.
I added a test case demonstrating this behavior, where the panic is caught and suppressed to allow CI to pass. This is left as a known issue to be addressed separately.

Make `ModuleBuilder::declare_function` return error on conflicting declarations (#91)
